### ISSUE TITLE
示例启动失败

### ISSUE THREAD

**Issue by chendongcse** [WeBankBlockchain/WeIdentity-Sample#52]
weid-sample 编译成功后，启动失败，报错如下：

2020-03-06 20:02:22.472 [main] ERROR SpringApplication() - Application startup failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'demoController': Unsatisfied dependency expressed through field 'demoService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoServiceImpl' defined in URL [jar:file:/root/fisco/weid-sample/dist/app/weid-sample.jar!/com/webank/weid/demo/service/impl/DemoServiceImpl.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.webank.weid.demo.service.impl.DemoServiceImpl]: Constructor threw exception; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at com.webank.weid.demo.server.SampleApp.main(SampleApp.java:41) [weid-sample.jar:?]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoServiceImpl' defined in URL [jar:file:/root/fisco/weid-sample/dist/app/weid-sample.jar!/com/webank/weid/demo/service/impl/DemoServiceImpl.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.webank.weid.demo.service.impl.DemoServiceImpl]: Constructor threw exception; nested exception is java.lang.ExceptionInInitializerError

**Comment by xuyuqin0123** [comment]
问题解决了吗

**Comment by Himtur** [comment]
我也遇到了同样的问题，请问解决了吗

**Comment by hsycc** [comment]
问题依旧存在。

**Comment by Ren-HK** [comment]
加入启动环境变量：
-Djdk.tls.namedGroups="secp256r1,secp256k1" -cp dist/app/*:resources/:dist/lib/*

**Comment by QQ-ing** [comment]
他们的文档写的有点问题.运行WeIdentity-Sample 需要先配置好weid-build-tools.
![image](https://user-images.githubusercontent.com/9510705/130422599-6d3102ac-9263-4cef-af0e-2b505d45c5cd.png)
这两步完成后,再clone WeIdentity-Sample并build. build完成后不要急着执行start.sh

1 先将 weid-build-tools/resources/* 下面所有的文件都拷贝到 WeIdentity-Sample/resources/ 下面,有重复的,直接替换掉.
2 将 weid-build-tools/output/admin/*  拷贝到 WeIdentity-Sample/keys/priv/ 下,
3 再执行start.sh脚本.

亲测成功.

**Comment by yanggang-JV** [comment]
> done
