### ISSUE TITLE
sample启动服务失败

### ISSUE THREAD

**Issue by ijavoracle** [WeBankBlockchain/WeIdentity-Sample#92]
《体验使用WeIdentity Sample》原文：
> > 若您在体验WeIdentity Sample之前已经完成WeIdentity Build Tool的部署和配置，weid-sample会自动从Build Tool中加载基本配置信息，无需您再次进行配置

按文档安装WeIdentity Build Tool时使用了默认版本（后经检查是1.3.0-rc1），fisco.properties中没有encrypt.type，导致sample启动服务失败。希望必要时在文档中对WeIdentity-Sample和WeIdentity Build Tool的版本要求做一些说明，谢谢。
2022-09-21 11:06:24.324 [main] ERROR SpringApplication(SpringApplication.java:856) - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'demoIssuerController': Unsatisfied dependency expressed through field 'demoService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoServiceImpl' defined in URL [jar:file:/opt/fisco/weid_sample/WeIdentity-Sample-master/dist/app/weIdentity-sample-1.0.11.jar!/com/webank/weid/demo/service/impl/DemoServiceImpl.class]: Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError
....................（省略）..............
Caused by: java.lang.NullPointerException
        at java.lang.String.contentEquals(String.java:1066) ~[?:1.8.0_342]
        at com.webank.weid.demo.common.util.FileUtil.loadConfigFromEnv(FileUtil.java:227) ~[weIdentity-sample-1.0.11.jar:?]
        at com.webank.weid.demo.service.impl.DemoServiceImpl.<clinit>(DemoServiceImpl.java:65) ~[weIdentity-sample-1.0.11.jar:?]

**Comment by youwenbusi** [comment]
配置文件自动寻找已修改，请用最新版本3.1.0及以上
